## Assignment 2.1:  Vectors, matrices and multidimensional arrays (Due: 2/19/20)

Adapted from Robert Johansson: Source code listings for [Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) (ISBN 978-1-484205-54-9).

The source code listings can be downloaded from http://www.apress.com/9781484205549

In [0]:
import numpy as np

### The NumPy array object

In [0]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [63]:
type(data)

numpy.ndarray

In [64]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
data.ndim

2

In [66]:
data.shape

(3, 2)

In [67]:
data.size

6

In [68]:
data.dtype

dtype('int64')

In [69]:
data.nbytes

48

### <font color = 'blue'> Exercise #1: </font> 
1. Create a 3-dimensional array of integers
2. Find all 3 of its dimensions, print them out one per line

In [0]:
n = 3
a = []
for x in range(n):
    a1 = []
    for y in range(n):
        a2 = []
        for z in range(n):
            a2.append(str(x)+str(y)+str(z))
        a1.append(a2)
    a.append(a1)

In [54]:
for x in a:
    print(x)

[['000', '001', '002'], ['010', '011', '012'], ['020', '021', '022']]
[['100', '101', '102'], ['110', '111', '112'], ['120', '121', '122']]
[['200', '201', '202'], ['210', '211', '212'], ['220', '221', '222']]


In [0]:
threed_array = np.random.randint(-10,10, size=(5,3,4))

In [0]:
threed_array.shape

(5, 3, 4)

In [0]:
for x in threed_array.shape:
    print(x)

5
3
4


## Data types

In [70]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [71]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [72]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [0]:
data = np.array([1, 2, 3], dtype=np.float)

In [75]:
data

array([1., 2., 3.])

In [76]:
data.dtype

dtype('float64')

In [0]:
data = np.array([1, 2, 3], dtype=np.int)

In [78]:
data.dtype

dtype('int64')

In [0]:
data

array([1, 2, 3])

In [0]:
data = np.array([1, 2, 3], dtype=np.float)

In [0]:
data

array([ 1.,  2.,  3.])

In [0]:
data.astype(np.int)

array([1, 2, 3])

In [0]:
d1 = np.array([1, 2, 3], dtype=float)

In [0]:
d2 = np.array([1, 2, 3], dtype=complex)

In [0]:
d1 + d2

array([ 2.+0.j,  4.+0.j,  6.+0.j])

In [0]:
(d1 + d2).dtype

dtype('complex128')

In [0]:
np.sqrt(np.array([-1, 0, 1]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([ nan,   0.,   1.])

In [0]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([ 0.+1.j,  0.+0.j,  1.+0.j])

### <font color = 'blue'> Exercise #2: </font>
1. Create a 2-dimensional numpy array of type float32
2. Add it to another of same dimensions but of type float64
3. Guess what type the entries of the sum array would be, and check your guess by carrying out the addition.

In [83]:
np.array([[1, 2],[2, 2],[3, 2]], dtype=np.float32)

array([[1., 2.],
       [2., 2.],
       [3., 2.]], dtype=float32)

In [84]:
np.array([[1, 2],[2, 2],[3, 2]], dtype=np.float64)

array([[1., 2.],
       [2., 2.],
       [3., 2.]])

### Real and imaginary parts

In [0]:
data = np.array([1, 2, 3], dtype=complex)

In [0]:
data

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [0]:
data.real

array([ 1.,  2.,  3.])

In [0]:
data.imag

array([ 0.,  0.,  0.])

## Creating arrays

### Arrays created from lists and other array-like objects

In [0]:
data = np.array(np.arange(16))

In [0]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [0]:
data.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
data = np.array([[1, 2], [3, 4]])

In [0]:
data.ndim

2

In [0]:
data.shape

(2, 2)

### Arrays filled with special constant values

In [0]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(4)

array([1., 1., 1., 1.])

In [0]:
data = np.ones(4)

In [0]:
data.dtype

dtype('float64')

In [0]:
data = np.ones(4, dtype=np.int64)

In [0]:
data.dtype

dtype('int64')

In [0]:
x1 = 5.4 * np.ones(10)

In [0]:
x2 = np.full(10, 5.4)

In [0]:
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [0]:
x1 = np.empty(5)

In [0]:
x1.fill(3.0)

In [0]:
x1

array([3., 3., 3., 3., 3.])

In [0]:
x2 = np.full(5, 3.0)

In [0]:
x2

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [0]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [0]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Arrays filled with logarithmic sequences

In [0]:
np.logspace(0, 2, 5)  # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

### Mesh-grid arrays

In [0]:
x = np.array([-1, 0, 1])

In [0]:
y = np.array([-2, 0, 2])

In [0]:
X, Y = np.meshgrid(x, y)

In [0]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [0]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

### <font color = 'blue'> Exercise #3: </font> Meshgrid produces the Cartesian product of the arrays, except that the x-values and y-values are kept seperate

1. Generate a meshgrid X,Y of x = a sequence of integers 1...5 and y of -1,0,1
2. How many entries will X have? Y?

In [0]:
Z = (X + Y) ** 2

In [0]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

In [0]:
x = np.array([1, 2, 3, 4, 5])

In [0]:
y = np.array([-1, 0, 1])

In [0]:
X, Y = np.meshgrid(x, y)

In [88]:
X

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [89]:
Y

array([[-1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1]])

### Creating uninitialized arrays

In [0]:
np.empty(3, dtype=np.float)

array([8.15931808e-312, 0.00000000e+000, 6.95229481e-310])

### Creating arrays with properties of other arrays

In [0]:
def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y

### Creating special matrix arrays

In [0]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [0]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [0]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

### One-dimensional arrays

In [0]:
a = np.arange(0, 11)

In [0]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
a[0]  # the first element

0

In [0]:
a[-1] # the last element

10

In [0]:
a[4]  # the fifth element, at index 4

4

In [0]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [0]:
a[:5]

array([0, 1, 2, 3, 4])

In [0]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [0]:
a[::-2]


array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [0]:
#The f is special function that takes two arguments m and n
f = lambda m, n: n + 10 * m
#The function is called with m=6, n = 6 to create a matrix (2-dim array)
A = np.fromfunction(f, (6, 6), dtype=int)
#prints it our
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [0]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [0]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [0]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [0]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [0]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [0]:
A[1::2, 1::3]  # every second element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views

In [0]:
B = A[1:5, 1:5]

In [0]:
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [0]:
#Be extremely careful here: we are not setting B to zeros, but also changing A[1:5, 1:5] also to zeros!!!
B[:, :] = 0

In [0]:
#As expected
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
#But is this expected?
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [0]:
#If we don't want to change the original matrix use .copy() function of the array object
C = B[1:3, 1:3].copy()

In [0]:
C

array([[0, 0],
       [0, 0]])

In [0]:
C[:, :] = 1  # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [0]:
C

array([[1, 1],
       [1, 1]])

In [0]:
#Chaing C contents does not affect B!
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <font color = 'blue'> Exercise #4 </font>:
1. Create an 2-dimensional numpy array of type int16
2. Add it to another of same dimensions but of type float64
3. Guess what type the entries of the sum array would be, and check your guess by carrying out the addition.

In [94]:
np.array([[1, 2],[2, 2],[3, 2]], dtype=np.int16)

array([[1, 2],
       [2, 2],
       [3, 2]], dtype=int16)

In [95]:
np.array([[1, 2],[2, 2],[3, 2]], dtype=np.float64)

array([[1., 2.],
       [2., 2.],
       [3., 2.]])

### Fancy indexing and Boolean-valued indexing

In [0]:
A = np.linspace(0, 1, 11)

In [0]:
A[np.array([0, 2, 4])]

array([ 0. ,  0.2,  0.4])

In [0]:
A[[0, 2, 4]]

array([ 0. ,  0.2,  0.4])

In [0]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [0]:
A[A > 0.5]

array([ 0.6,  0.7,  0.8,  0.9,  1. ])

In [0]:
A = np.arange(10)

In [0]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
indices = [2, 4, 6]

In [0]:
B = A[indices]

In [0]:
B[0] = -1  # this does not affect A

In [0]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
A[indices] = -1

In [0]:
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [0]:
A = np.arange(10)

In [0]:
B = A[A > 5]

In [0]:
B[0] = -1  # this does not affect A

In [0]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
A[A > 5] = -1

In [0]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

## Reshaping and resizing

In [0]:
data = np.array([[1, 2], [3, 4]])

In [0]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [0]:
data.reshape(4)

array([1, 2, 3, 4])

In [0]:
data = np.array([[1, 2], [3, 4]])

In [0]:
data

array([[1, 2],
       [3, 4]])

In [109]:
data.flatten()

array([1., 2., 2., 2., 3., 2.], dtype=float32)

In [0]:
data.flatten().shape

(4,)

In [0]:
data = np.arange(0, 5)

In [0]:
column = data[:, np.newaxis]

In [0]:
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
row = data[np.newaxis, :]

In [0]:
row

array([[0, 1, 2, 3, 4]])

In [0]:
data = np.arange(5)

In [0]:
data

array([0, 1, 2, 3, 4])

In [0]:
data = np.arange(9)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
data.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [0]:
data = np.random.randn(4, 3)

In [0]:
data.shape

(4, 3)

In [0]:
data.T.shape

(3, 4)

In [0]:
np.vstack((data, data, data)).shape

(12, 3)

In [0]:
data = np.arange(5)

In [0]:
data

array([0, 1, 2, 3, 4])

In [0]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [0]:
data = data[:, np.newaxis]

In [0]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

### <font color = 'blue'> Exercise #5 </font>
- Create a three dimensional array of size 3 x 3 x 4 of random integers named A
- Stack 3 copies of the A vertically and name it B.  Can you guess the dimensions of the resulting array?
- Now stack 3 copies of the transpose of A horizontally, and name it C.  Can you guess the dimension of C? Is it same as that of B?
- Now use the flatten() method of A, call the result A_flat.  What is the shape of A_flat?
- Reconstruct A from A_flat using reshape() method

In [0]:
A=np.array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [0]:
B=np.array([[[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]],
       [[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]],
       [[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]]])

In [103]:
B.ndim

3

In [0]:
C=np.transpose(B)

In [105]:
C

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]],

       [[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]],

       [[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]])

In [106]:
C.ndim

3

In [0]:
A_flat= A.flatten()

In [111]:
A_flat

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [112]:
A.flatten().shape

(15,)

## Vectorized expressions

### Arithmetic operations

In [0]:
x = np.array([[1, 2], [3, 4]]) 

In [0]:
y = np.array([[5, 6], [7, 8]])

In [0]:
x + y

array([[ 6,  8],
       [10, 12]])

In [0]:
y - x

array([[4, 4],
       [4, 4]])

In [0]:
x * y

array([[ 5, 12],
       [21, 32]])

In [0]:
y / x

array([[ 5.        ,  3.        ],
       [ 2.33333333,  2.        ]])

In [0]:
x * 2

array([[2, 4],
       [6, 8]])

In [0]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [0]:
y / 2

array([[ 2.5,  3. ],
       [ 3.5,  4. ]])

In [0]:
(y / 2).dtype

dtype('float64')

In [0]:
x = np.array([1, 2, 3, 4]).reshape(2,2)

In [0]:
z = np.array([1, 2, 3, 4])

In [0]:
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [0]:
z = np.array([[2, 4]])

In [0]:
z

array([[2, 4]])

In [0]:
z.shape

(1, 2)

In [0]:
x / z

array([[ 0.5,  0.5],
       [ 1.5,  1. ]])

In [0]:
zz = np.concatenate([z, z], axis=0)

In [0]:
zz

array([[2, 4],
       [2, 4]])

In [0]:
x / zz

array([[ 0.5,  0.5],
       [ 1.5,  1. ]])

In [0]:
z = np.array([[2], [4]])

In [0]:
z.shape

(2, 1)

In [0]:
x / z

array([[ 0.5 ,  1.  ],
       [ 0.75,  1.  ]])

In [0]:
zz = np.concatenate([z, z], axis=1)

In [0]:
zz

array([[2, 2],
       [4, 4]])

In [0]:
x / zz

array([[ 0.5 ,  1.  ],
       [ 0.75,  1.  ]])

In [0]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

array([[ 6,  9],
       [ 9, 12]])

In [0]:
x = np.array([[1, 3], [2, 4]])
x += y
x

array([[ 6,  9],
       [ 9, 12]])

### Elementwise functions

In [0]:
x = np.linspace(-1, 1, 11)

In [0]:
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [0]:
y = np.sin(np.pi * x)

In [0]:
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [0]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
def heaviside(x):
    return 1 if x > 0 else 0

In [0]:
heaviside(-1)

0

In [0]:
heaviside(1.5)

1

In [0]:
x = np.linspace(-5, 5, 11)

In [0]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [0]:
heaviside = np.vectorize(heaviside)

In [0]:
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [0]:
def heaviside(x):
    return 1.0 * (x > 0)

### <font color = 'blue'> Exercise #6 </font>  

1.  Create a function "sigmoid" that takes one variable $x$ as input and returns $\frac{1}{1 + e^{-x}}$ as output
2.  Create a 2-dimensional array A of random numbers of size 3x4
3.  Let S = sigmoid(A).  Print S

**Note this is an example of broadcasting: applying an operation to every element of an object, where the operation was only meant between elements**

### Aggregate functions

In [0]:
data = np.random.normal(size=(15,15))

In [0]:
np.mean(data)

-0.074403636812459123

In [0]:
data.mean()

-0.074403636812459123

In [0]:
data = np.random.normal(size=(5, 10, 15))

In [0]:
data.sum(axis=0).shape

(10, 15)

In [0]:
data.sum(axis=(0, 2)).shape

(10,)

In [0]:
data.sum()

11.003615133940048

In [0]:
data = np.arange(1,10).reshape(3,3)

In [0]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
data.sum()

45

In [0]:
data.sum(axis=0)

array([12, 15, 18])

In [0]:
data.sum(axis=1)

array([ 6, 15, 24])

### Boolean arrays

In [0]:
a = np.array([1, 2, 3, 4])

In [0]:
b = np.array([4, 3, 2, 1])

In [0]:
a < b

array([ True,  True, False, False], dtype=bool)

In [0]:
np.all(a < b)

False

In [0]:
np.any(a < b)

True

In [0]:
x = np.array([-2, -1, 0, 1, 2])

In [0]:
x > 0

array([False, False, False,  True,  True], dtype=bool)

In [0]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [0]:
x * (x > 0)

array([0, 0, 0, 1, 2])

# Set operations

In [0]:
a = np.unique([1,2,3,3])

In [0]:
b = np.unique([2,3,4,4,5,6,5])

In [37]:
np.in1d(a, b)

array([False,  True,  True])

In [0]:
1 in a

True

In [0]:
1 in b

False

In [0]:
np.all(np.in1d(a, b))

False

In [0]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [0]:
np.intersect1d(a, b)

array([2, 3])

In [0]:
np.setdiff1d(a, b)

array([1])

In [0]:
np.setdiff1d(b, a)

array([4, 5, 6])

### <font color = 'blue'> Exercise #7 </font> 
1.  Let the **list** L = ['M', 'A', 'S', 'S', 'A', 'C', 'H', 'U', 'S', 'E', 'T', 'S']
2.  Use the **set** operation to find the unique entries in the list, call it S.  
3.  Use the **zip** operation to now create Z = ordered pairs unique entries of L in alphabatical order with integer 0, 1, 2, 3 etc. 
4.  Print the entries of Z

In [0]:
L = ['M', 'A', 'S', 'S', 'A', 'C', 'H', 'U', 'S', 'E', 'T', 'S']

In [0]:
S=np.unique(['M','C','H','U','E','T'])

In [46]:
np.in1d(L, S)

array([ True, False, False, False, False,  True,  True,  True, False,
        True,  True, False])

In [47]:
np.all(np.in1d(L, S))

False

In [49]:
np.union1d(L, S)

array(['A', 'C', 'E', 'H', 'M', 'S', 'T', 'U'], dtype='<U1')

In [50]:
np.intersect1d(L, S)

array(['C', 'E', 'H', 'M', 'T', 'U'], dtype='<U1')

In [51]:
np.setdiff1d(L, S)

array(['A', 'S'], dtype='<U1')

In [52]:
np.setdiff1d(L, S)

array(['A', 'S'], dtype='<U1')

## Matrix and vector operations

In [0]:
A = np.arange(1, 7).reshape(2, 3)

In [0]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
B = np.arange(1, 7).reshape(3, 2)

In [0]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [0]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [0]:
A = np.arange(9).reshape(3, 3)

In [0]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
x = np.arange(3)

In [0]:
x

array([0, 1, 2])

In [0]:
np.dot(A, x)

array([ 5, 14, 23])

In [0]:
A.dot(x)

array([ 5, 14, 23])

In [0]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

In [0]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [0]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [0]:
A = np.matrix(A)

In [0]:
B = np.matrix(B)

In [0]:
Ap = B * A * B.I

In [0]:
A = np.asmatrix(A)

In [0]:
B = np.asmatrix(B)

In [0]:
Ap = B * A * B.I

In [0]:
Ap = np.asarray(Ap)

In [0]:
np.inner(x, x)

5

In [0]:
np.dot(x, x)

5

In [0]:
y = x[:, np.newaxis]

In [0]:
y

array([[0],
       [1],
       [2]])

In [0]:
np.dot(y.T, y)

array([[5]])

In [0]:
x = np.array([1, 2, 3])

In [0]:
np.outer(x, x) 

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [0]:
np.kron(x, x) 

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [0]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [0]:
np.kron(np.ones((2,2)), np.identity(2))

array([[ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.]])

In [0]:
np.kron(np.identity(2), np.ones((2,2)))

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  1.,  1.]])

In [0]:
x = np.array([1, 2, 3, 4])

In [0]:
y = np.array([5, 6, 7, 8])

In [0]:
np.einsum("n,n", x, y)

70

In [0]:
np.inner(x, y)

70

In [0]:
A = np.arange(9).reshape(3, 3)

In [0]:
B = A.T

In [0]:
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [0]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True